name: "ecommerce"

services:
  postgres:
    container_name: "postgres"
    hostname: "postgres"
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    image: postgres:dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
      POSTGRES_DB: "ecommerce"
    volumes:
      - postgres_volume:/var/lib/postgresql
    networks:
      - app_network

  app:
    container_name: "api"
    hostname: "api"
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - COMPOSER_VERSION=${COMPOSER_VERSION}
    image: ecommerce:api-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/backend
    networks:
      - app_network
    depends_on:
      - postgres

networks:
  app_network:
    driver: bridge

volumes:
  postgres_volume:
    driver: local
